### ISSUE TITLE
后台向前台传session，前台获取不到

### ISSUE THREAD

**Issue by WeCanDoing** [WeCanDoing/Blogs#1]
- 本来是想实现登陆后菜单栏显示用户名的功能，然而发现似乎无法获取session.
loginController中
`session.setAttribute("name", user.getName());
			response.sendRedirect("/index");
		    `
前台thmyleaf如何获取session?
![微信截图_20190521151807](https://user-images.githubusercontent.com/47911106/58076008-ab175c80-7bdb-11e9-8eac-1ea4a489f34f.png)
前台如何取值<h1>
![微信截图_20190521151957](https://user-images.githubusercontent.com/47911106/58076114-f7629c80-7bdb-11e9-81ae-d74559fc98f8.png)

**Comment by WeCanDoing** [comment]
使用<p id="demo" th:text="${session.name}"></p> 中${session.name} 可以获取值

**Comment by nanjolono** [comment]
> 使用
> 
> 中${session.name} 可以获取值
已解决
